import Head from 'next/head'

import { Inter } from '@next/font/google'
import { Footer } from '../Components/Footer'
import { Home } from './Home'
import { AppNavbar } from '../Components/AppNavBar'
const inter = Inter({ subsets: ['latin'] })


export default function Index() {
  return (
    <>
      <Head>
        <title>Cyber Chipset</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
     <main >
        <Home/>
      </main>
    </>
  )
}
