import Head from 'next/head'

import { Inter } from '@next/font/google'
import { stripe } from '../utils/stripe'
import Stripe from 'stripe'
import { Comments } from '../Components/Home/Comments'
import { ConsultHome } from '../Components/Home/ConsultHome'
import { FeatureBusiness } from '../Components/Home/FeaturesBusiness'
import { Hero } from '../Components/Home/Hero'
import { InfoAbouteSites } from '../Components/Home/InfoAboutSites'
import { MobileProduct } from '../Components/Home/MobileProduct'
import { PricesHome } from '../Components/Home/PricesHome'
import { Process } from '../Components/Home/Process'
import { QuestionAnswers } from '../Components/Home/QuentionsAnswers'
import { SolutionCustumer } from '../Components/Home/SolutionCustumer'
const inter = Inter({ subsets: ['latin'] })

export interface ProductsProps{
  products:{
    id:string
    name:string
    price: number
  }[]
}

export default function Index({products}:ProductsProps) {

  return (
    <>
      <Head>
        <title>Cyber Chipset</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
     <main >

      <Hero/>
      <Process/>
      <ConsultHome/>
      
{   <FeatureBusiness/>
    }
    <SolutionCustumer/>
    <InfoAbouteSites/>
    <PricesHome products={products} />
    <MobileProduct/>
    <Comments/>
      <QuestionAnswers/>
      </main>
    </>
  )
}
export async function getServerSideProps<GetServerSideProps>() {
  const response = await stripe.products.list({expand:["data.default_price"]})
  const products = response.data.map(product=>{
    const prices = product.default_price as Stripe.Price
    return{
      id:product.id,
      name:product.name,
      price: prices.unit_amount as number/100
    }
  })
  
  return {
    props: {
      name:"leo",
     products
    }, // will be passed to the page component as props
  }
}